set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-yank'
#theme
set -g @plugin 'catppuccin/tmux'
set -g @catppuccin_flavor "mocha"
set -g @catppuccin_window_status_style "rounded"

set -g status-right-length 100
set -g status-left-length 100
set -g status-left ""
set -g status-right "#{E:@catppuccin_status_application}"

set -g mouse on
set -g default-terminal "tmux-256color"
set-option -sa terminal-overrides ",xterm*:Tc"
set-option -sa terminal-features ',xterm-kitty:RGB'
set -g cursor-style block
set -g mouse on
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on
set-window-option -g mode-keys vi
set-option -g allow-rename on
set -sg escape-time 0 # more fluent escape key
set -sg repeat-time 0 # more responsive pane switching
set-window-option -g mode-keys vi # vi mode

bind r source-file ~/.tmux.conf \; display-message "~/.tmux.conf reloaded."

# pane
bind "-" split-window -v -c "#{pane_current_path}"
bind "\\" split-window -h -c "#{pane_current_path}"
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

#window
bind c new-window -c "#{pane_current_path}"

run '~/.tmux/plugins/tpm/tpm'
