hl.env("XMODIFIERS", "@im=fcitx5")
hl.env("QT_IM_MODULES", "wayland;fcitx")
hl.env("INPUT_METHOD", "fcitx")
hl.env("SDL_IM_MODULE", "fcitx")
hl.env("QT_QPA_PLATFORMTHEME", "gtk3")
hl.env("QT_QPA_PLATFORM", "wayland;xcb")
hl.env("LANG", "zh_CN.UTF-8")
