###################
### KEYBINDINGS ###
###################
$terminal=kitty
$browser=firefox
$launcher=vicinae toggle
# See https://wiki.hypr.land/Configuring/Keywords/
$mod = ALT # Sets "Windows" key as main modifier

# Example binds, see https://wiki.hypr.land/Configuring/Binds/ for more
bind = $mod, Semicolon, exec, $terminal
bind = $mod, Apostrophe, exec, $browser
bind = $mod, q, killactive,
bind = $mod, m, exit,
bind = $mod, v, togglefloating,
bind = $mod, Space, exec, $launcher 
bind = $mod, f, fullscreen

# Move focus with mainMod + arrow keys
bind = $mod, h, movefocus, l
bind = $mod, l, movefocus, r
bind = $mod, k, movefocus, u
bind = $mod, j, movefocus, d

# Switch workspaces with mainMod + [0-9]
bind = $mod, 1, workspace, 1
bind = $mod, 2, workspace, 2
bind = $mod, 3, workspace, 3
bind = $mod, 4, workspace, 4
bind = $mod, 5, workspace, 5
bind = $mod, 6, workspace, 6
bind = $mod, 7, workspace, 7
bind = $mod, 8, workspace, 8
bind = $mod, 9, workspace, 9
bind = $mod, 0, workspace, 10

# Move active window to a workspace with mainMod + SHIFT + [0-9]
bind = $mod CTRL, 1, movetoworkspace, 1
bind = $mod CTRL, 2, movetoworkspace, 2
bind = $mod CTRL, 3, movetoworkspace, 3
bind = $mod CTRL, 4, movetoworkspace, 4
bind = $mod CTRL, 5, movetoworkspace, 5
bind = $mod CTRL, 6, movetoworkspace, 6
bind = $mod CTRL, 7, movetoworkspace, 7
bind = $mod CTRL, 8, movetoworkspace, 8
bind = $mod CTRL, 9, movetoworkspace, 9
bind = $mod CTRL, 0, movetoworkspace, 10

# Example special workspace (scratchpad)
bind = $mod, S, togglespecialworkspace, magic
bind = $mod SHIFT, S, movetoworkspace, special:magic

# Scroll through existing workspaces with mainMod + scroll
bind = $mod, mouse_down, workspace, e+1
bind = $mod, mouse_up, workspace, e-1

# Move/resize windows with mainMod + LMB/RMB and dragging
bindm = $mod, mouse:272, movewindow
bindm = $mod, mouse:273, resizewindow

# Laptop multimedia keys for volume and LCD brightness
bindel = ,XF86AudioRaiseVolume, exec, wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+
bindel = ,XF86AudioLowerVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-
bindel = ,XF86AudioMute, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
bindel = ,XF86AudioMicMute, exec, wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle
bindel = ,XF86MonBrightnessUp, exec, brightnessctl -e4 -n2 set 5%+
bindel = ,XF86MonBrightnessDown, exec, brightnessctl -e4 -n2 set 5%-

# Requires playerctl
bindl = , XF86AudioNext, exec, playerctl next
bindl = , XF86AudioPause, exec, playerctl play-pause
bindl = , XF86AudioPlay, exec, playerctl play-pause
bindl = , XF86AudioPrev, exec, playerctl previous
