set positional-arguments

@default:
    just --list

@init:
    nix run github:nix-community/nix-init

@up:
    nix flake update --commit-lock-file

@clean:
    sudo nix profile wipe-history --profile /nix/var/nix/profiles/system --older-than 7d

@gc:
    sudo nix-collect-garbage --delete-older-than 7d

    nix-collect-garbage --delete-older-than 7d

[linux]
[group('nix')]
sh *pkgs = "git neovim":
    #!/usr/bin/env bash
    set -euxo pipefail
    source scripts/prefix.sh "$@"

@dev *env="dev":
    nix develop .#{{ env }}

@deploy target="wsl":
    sudo nixos-rebuild switch --flake .#{{ target }}

@fix:
    nix-store --repair --verify # --check-contents

@genfacter:
    nix run github:numtide/nixos-facter -- -o facter.json

@fast-deploy target="wsl":
    nix run github:Mic92/nix-fast-build -- --flake .#nixosConfigurations.{{ target }}.config.system.build.toplevel --skip-cached --eval-max-memory-size 15360

@fast-build target="":
    nix run github:Mic92/nix-fast-build -- --flake .#packages.x86_64-linux.{{ target }} --eval-max-memory-size 15360
