require("config.options")
require("config.keymaps")
require("config.autocmds")
require("config.lsp")

require("plugins.theme")
require("plugins.lsp")
require("plugins.cmp")
require("plugins.treesitter")
require("plugins.statusline")
require("plugins.oil")
require("plugins.fmt")
require("plugins.text-editing")
require("plugins.icon")
require("plugins.markdown")
require("plugins.snacks")
